### ISSUE TITLE
Die Aufgabenstellung ist veraltet

### ISSUE THREAD

**Issue by ghost** [Nils-DataCraft/Tagesaufgaben_GIT_Titanic#1]
Es stehen zwei Sätze in der README.md, die keinen Sinn machen und Aufgaben darstellen, die nicht lösbar sind.

# Wo tritt das Problem auf?

**Fehlermeldung**

Lösungsvorschläge

**Comment by ghost** [comment]
Ich kann das leider nicht lösen. Kann @iManu93 mir helfen?

**Comment by ghost** [comment]
Habe die Aufgabenstellung verbessert!

**Comment by iManu93** [comment]
Ja @Nils-DataCraft;, ist erledigt.
